### ISSUE TITLE
Improve instructions on using --jsonFile

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/wsi-to-dicom-converter#34]
Improve the help comments by describing the format of the JSON file and add a section to the README that shows an example of using this feature.

**Comment by pavertomato** [comment]
we used to have description of parameters in readme, should it be reverted or only "jsonFile" should be described?
https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/commit/0d83964583a485039a15b7927ddf5e258fe3d77b#diff-04c6e90faac2675aa89e2176d2eec7d8L65
