### ISSUE TITLE
Investigate OpenSlide issue that leads to blacked out squares

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/wsi-to-dicom-converter#36]
We have a workaround where we drop the first row/column, but this issue is tracking the underlying fix.

Issue in OpenSilde: https://github.com/openslide/openslide/issues/268.

**Comment by danielbeaudreau** [comment]
Hi Egor, can you please take a look at this?

**Comment by dzelemba** [comment]
Latest status here is that the openslide project doesn't have any active maintainers, so there isn't much we can do for now.

**Comment by danielbeaudreau** [comment]
Thanks
