### ISSUE TITLE
Can it handle .ndpi Z-stack image?

### ISSUE THREAD

**Issue by Yuvi-416** [GoogleCloudPlatform/wsi-to-dicom-converter#40]
Can it handle .ndpi Z-stack image?

**Comment by dzelemba** [comment]
This tool uses [OpenSlide](https://openslide.org) to read various WSI formats and OpenSlide does support NDPI: https://openslide.org/formats/hamamatsu/, but OpenSlide does not support multiple focal planes: https://github.com/openslide/openslide/issues/31. Let me know if this answers your question.

**Comment by Yuvi-416** [comment]
Hello there,
Thanks for your suggestion, it solved my queries.
Do you know any libraries in python which can handle this kind of image?

**Comment by dzelemba** [comment]
No I'm not sure sorry, you could try and check out BioFormats: https://www.openmicroscopy.org/bio-formats/.
