### ISSUE TITLE
how can I make OUTPUT to be a single dicom file with multiple levels?

### ISSUE THREAD

**Issue by VincePlantItAi** [GoogleCloudPlatform/wsi-to-dicom-converter#56]
First of all, THANK YOU!, for creating this awesome stuff.

Hi, I am trying to build a web application, a dicom file viewer, for personal project.

I need to convert all my svs files to dicom files.
And it seems like outputs are always N number of files, being equivalent to number of levels.

so how can I make OUTPUT to be a single dicom file with multiple levels?

it d be nice if I can get at least hint from you guys... :((((

thank you in advance~!

cheers, from Seoul

**Comment by danielbeaudreau** [comment]
Hi, multiple levels per file is not supported by the tool at the moment.
